---
title: "ProyectoTD2026"
author: "FJavierBailachCastilla"
date: "`r Sys.Date()`"
output: pdf_document
---

ESTE RMD SE USARÁ PARA MANIPULAR LOS DATOS, LUEGO PASAREMOS TODA LA INFORMACIÓN
AL ESQUELETO mdpi modificado
https://aulavirtual.uv.es/mod/resource/view.php?id=3579580

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#LIBRERÍAS
```{r}
###REVISAR EL ARCHIVO paketes.R
library(readr)
library(dplyr)
library(lubridate)
library(stringr)
library(forcats)
library(tidyr)
```

#CARGA DE DATOS
```{r}
library(readr)
logdata <- read_csv("data/logs_moodle_anon.csv", 
    na = "NA")

head(logdata)
tail(logdata)
```


```{r}
#Definimos una función llamada procesa_logs_moodle. Esta función está diseñada para leer, limpiar y transformar un archivo de logs de Moodle, convirtiendo los datos en un data frame estructurado y listo para su análisis. La función no utiliza realmente el algumento de entrada, ya que carga directamente el archivo csv predefinido con los logs.

procesar_logs_moodle <- function(logdata) {
  logdata <- read_csv("data/logs_moodle_anon.csv")
  
#Renombramos las columnas, para que sean más manejables, quitando espacios o cambiando los nombres más largos a otros más cortos
  logdata <- logdata %>%
    rename(
      hora = `Hora`,
      usuario = `Nombre completo del usuario`,
      usuario_afectado = `Usuario afectado`,
      contexto = `Contexto del evento`,
      componente = `Componente`,
      evento = `Nombre evento`,
      descripcion = `Descripción`,
      origen = `Origen`,
      ip = `Dirección IP`
    )

  # Conversión variable Hora 
  logdata <- logdata %>%
    mutate(
      hora = str_replace(hora, ",", ""), #elimino la coma 
      hora = dmy_hms(hora), #texto en formato fecha-hora 
    )


  #Creación columnas fecha, hora_dia y dia_semana
  logdata <- logdata %>%
    mutate(
      fecha = as_date(hora),
      hora_dia = hour(hora),
      dia_semana = wday(hora, label = TRUE)
    )

  # Ordeno los registros por fecha y hora de más antigup a más reciente
  logdata <- logdata %>%
    arrange(hora)

  return(logdata)
}
```

```{r}
#Como se veria el dataset ya limpio y organizado
logdata <- read_csv("data/logs_moodle_anon.csv")
logs <- procesar_logs_moodle(logdata)

```

```{r}
#Comprobamos que los tipos de las variables son correctos y vemos mediante summary si sus valores son coherentes.
summary(logs)

```

```{r}
#Analizamos los datos perdidos(NA) de cada una de las variables del .csv
na_por_variable <- logs %>%
  summarise(across(everything(), ~sum(is.na(.)))) %>%
  pivot_longer(everything(), 
               names_to = "variable", 
               values_to = "n_NA") %>%
  filter(n_NA > 0)

na_por_variable
```

```{r}
#Tabla 1
#Esta tabla nos enseña mediante la frecuencia las zonas donde más tráfico hay a la hora del ingreso de un usuario en el aula virtual.
tabla_componentes <- logs %>%
  group_by(componente) %>%
  summarise(Frecuencia = n()) %>%
  arrange(desc(Frecuencia)) %>%
  rename(Componente = componente)

tabla_componentes

```

